### ISSUE TITLE
I need latest version 2.x,thx!

### ISSUE THREAD

**Issue by hegelsu** [NAXAM/rxjava-android-binding#1]
I need latest version 2.x,thx!

**Comment by tuyen-vuduc** [comment]
You could fork our repo then create appropriate binding for RxJava 2x. We are then happy to merge back and publish new version.

If you couldn't do but need it urgently, plz contact me at tuyen@naxam.net for a price.

**Comment by hegelsu** [comment]
Ok, thx.
